seed: 88
n_splits: 5
n_extract_features: 10
pipe_config_path: 'configs/pipe_configs.yaml'
db_name: 'ibd_microbiome.sqlite3'
log_name: "status.log"

split_cohorts:
  train_U1: ['USA_hmbp', 'USA_qiita', 'USA_umass']
  validate_U1: ['USA_prism']

  train_U2: ['USA_prism', 'USA_qiita', 'USA_umass']
  validate_U2: ['USA_hmbp']

  train_A1: ['USA_hmbp', 'China_jia', 'Germany_elinav']
  validate_A1: ['Ireland_hill']

  train_A2: ['USA_hmbp', 'Ireland_hill', 'Germany_elinav']
  validate_A2: ['China_jia']
  
  train_B1: ['USA_hmbp', 'China_jia', 'Israel_elinav']
  validate_B1: ['Ireland_hill']

  train_B2: ['Ireland_hill', 'USA_hmbp', 'Israel_elinav']
  validate_B2: ['China_jia']

  train_C1: ['USA_hmbp', 'Germany_elinav', 'Ireland_hill'] 
  validate_C1: ['Israel_elinav']

  train_C2: ['Ireland_hill', 'USA_hmbp', 'Israel_elinav']
  validate_C2: ['Germany_elinav']

  train_D1: ['USA_hmbp', 'Germany_elinav', 'China_jia']
  validate_D1: ['Israel_elinav']

  train_D2: ['USA_hmbp', 'China_jia', 'Israel_elinav']
  validate_D2: ['Germany_elinav']

  train_E1: ['Ireland_hill', 'China_jia', 'Germany_elinav']
  validate_E1: ['Israel_elinav']

  train_E2: ['Ireland_hill', 'Israel_elinav', 'Germany_elinav']
  validate_E2: ['China_jia']

  train_F1: ['Ireland_hill', 'China_jia', 'Germany_elinav']
  validate_F1: ['USA_hmbp']
  
  train_F2: ['Ireland_hill', 'Israel_elinav', 'Germany_elinav']
  validate_F2: ['USA_prism']

  evaluate_israel: ['Israel_elinav']
  evaluate_germany: ['Germany_elinav']
  evaluate_china: ['China_jia']
  evaluate_ireland: ['Ireland_hill']